### ISSUE TITLE
Failed to Include: `<assimp/config.h>`

### ISSUE THREAD

**Issue by Polytonic** [assimp/assimp#1566]
I'm running into this shell output as of 98a1b76 in which it fails to include the config header. This is from a clean build. I also observed output earlier similar to that listed in #1553 though I can't easily confirm at this time if they're related. Any ideas on how I might fix this?

**Truncated Shell Output**
```sh
rm -rf * && cmake .. && make

...

In file included from ../Glitter/Vendor/assimp/include/assimp/Importer.hpp:55:
In file included from ../Glitter/Vendor/assimp/include/assimp/types.h:57:
    ../Glitter/Vendor/assimp/include/assimp/defs.h:52:10: fatal error: 'assimp/config.h'
          file not found
#include <assimp/config.h>
```

**Compiler**
```yml
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I am building on an Apple MacBook Pro 11,3 running macOS 10.13.1. If you have a similar config on hand, you should theoretically be able to reproduce the log by compiling my `Glitter` project with the `assimp` submodule updated to latest. (?)
