### ISSUE TITLE
pyassimp materials

### ISSUE THREAD

**Issue by Yves33** [assimp/assimp#3520]
when loading a model with pyassimp (tried with 5.0.1 both on windows and GNU/linux), 
- the model names, shadingnm, file and uvwsrc are unreadable. 
- scene.textures is empty (maybe normal as I'm trying with obj)

Steps to reproduce:
```
scene=pyassimp.load("./OBJ/spider.obj",processing=pyassimp.postprocess.aiProcess_Triangulate)
print("MATERIALS:")
for index, material in enumerate(scene.materials[-1:]):
    print("  MATERIAL (id:" + str(index+1) + ")")
        for key, value in material.properties.items():
            print("    %s: %s" % (key, value))
print("TEXTURES:",len(scene.textures))
```
output

```
MATERIAL:
LAST  MATERIAL
    name: b'\x08\x00\x00'
    shadingm: b'\x02\x00\x00\x00'
    ambient: 205
    diffuse: 205
    specular: 0
    emissive: 0
    shininess: 0
    opacity: 0
    transparent: 0
    refracti: 0
    file: b'\x12\x00\x00'
    uvwsrc: b'\x00\x00\x00\x00'
NB TEXTURES: 0
```

what would be the correct way to decode the strings name, shadingm,file and uvwsrc?

thanks
